services:
  uniplus-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      PUBLIC_BASE_URL: http://localhost:3000
      RUN_DB_MIGRATIONS: "true"
      UNIPLUS_SERVER_URL: ${UNIPLUS_SERVER_URL}
      UNIPLUS_BASE_URL: ${UNIPLUS_BASE_URL}
      UNIPLUS_AUTH_BASIC: ${UNIPLUS_AUTH_BASIC}
      UNIPLUS_TOKEN: ${UNIPLUS_TOKEN}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      DATABASE_URL: ${DATABASE_URL}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASS: ${BASIC_AUTH_PASS}
